# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: localhost
  database: climate_awareness_backend_development
  username: abdub
  password: abdub123

test:
  <<: *default
  database: climate_awareness_backend_test

production:
  <<: *default
  database: climate_awareness_backend_production
  username: abdub
  password: <%= ENV['DATABASE_PASSWORD'] %>